### ISSUE TITLE
Sample.get_vec Bug

### ISSUE THREAD

**Issue by Gers2017** [Vaimer9/aoc_solutions#2]
Hi @Vaimer9, please check this [branch](https://github.com/Gers2017/vaimer9_aoc_solutions/tree/input-bug) I made to test the Sample struct.
Specifically [day03](https://github.com/Gers2017/vaimer9_aoc_solutions/blob/input-bug/2022/day3/src/main.rs) and run the code.
- There's a new file "small_sample.txt"
- I'm using the `include_str!` macro and the `Sample.get_vec()`

**Comment by Vaimer9** [comment]
Thanks a lot for finding that. You can make a PR that fixes this and I'll merge it ASAP.
